In [1]:
# Risa Luthor
# September 1st, 2023
#CS 379 IP 1

In [2]:
# Import Libraries
import pandas as pd
import numpy as np

In [3]:
# Import the Titanic Passenger Data Set
file = 'TitanicPassengerDataSet.xlsx'
df = pd.read_excel(file)

In [4]:
#Print the start and end of the Data list. Showing the Data set as read file
df

pclass  survived                                             name  \
0          1         1                    Allen, Miss. Elisabeth Walton   
1          1         1                   Allison, Master. Hudson Trevor   
2          1         0                     Allison, Miss. Helen Loraine   
3          1         0             Allison, Mr. Hudson Joshua Creighton   
4          1         0  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)   
...      ...       ...                                              ...   
1304       3         0                             Zabour, Miss. Hileni   
1305       3         0                            Zabour, Miss. Thamine   
1306       3         0                        Zakarian, Mr. Mapriededer   
1307       3         0                              Zakarian, Mr. Ortin   
1308       3         0                               Zimmerman, Mr. Leo   

         sex      age  sibsp  parch  ticket      fare    cabin embarked boat  \
0     female  29.0000      0      0   24160  211.3375       B5        S    2   
1       male   0.9167      1      2  113781  151.5500  C22 C26        S   11   
2     female   2.0000      1      2  113781  151.5500  C22 C26        S  NaN   
3       male  30.0000      1      2  113781  151.5500  C22 C26        S  NaN   
4     female  25.0000      1      2  113781  151.5500  C22 C26        S  NaN   
...      ...      ...    ...    ...     ...       ...      ...      ...  ...   
1304  female  14.5000      1      0    2665   14.4542      NaN        C  NaN   
1305  female      NaN      1      0    2665   14.4542      NaN        C  NaN   
1306    male  26.5000      0      0    2656    7.2250      NaN        C  NaN   
1307    male  27.0000      0      0    2670    7.2250      NaN        C  NaN   
1308    male  29.0000      0      0  315082    7.8750      NaN        S  NaN   

       body                        home.dest  
0       NaN                     St Louis, MO  
1       NaN  Montreal, PQ / Chesterville, ON  
2       NaN  Montreal, PQ / Chesterville, ON  
3     135.0  Montreal, PQ / Chesterville, ON  
4       NaN  Montreal, PQ / Chesterville, ON  
...     ...                              ...  
1304  328.0                              NaN  
1305    NaN                              NaN  
1306  304.0                              NaN  
1307    NaN                              NaN  
1308    NaN                              NaN  

[1309 rows x 14 columns]

In [5]:
# Provides a shorter and easier to read list of averages of the full list
df.describe()

pclass     survived          age        sibsp        parch  \
count  1309.000000  1309.000000  1046.000000  1309.000000  1309.000000   
mean      2.294882     0.381971    29.881135     0.498854     0.385027   
std       0.837836     0.486055    14.413500     1.041658     0.865560   
min       1.000000     0.000000     0.166700     0.000000     0.000000   
25%       2.000000     0.000000    21.000000     0.000000     0.000000   
50%       3.000000     0.000000    28.000000     0.000000     0.000000   
75%       3.000000     1.000000    39.000000     1.000000     0.000000   
max       3.000000     1.000000    80.000000     8.000000     9.000000   

              fare        body  
count  1308.000000  121.000000  
mean     33.295479  160.809917  
std      51.758668   97.696922  
min       0.000000    1.000000  
25%       7.895800   72.000000  
50%      14.454200  155.000000  
75%      31.275000  256.000000  
max     512.329200  328.000000

In [6]:
# This will show what categories have no values within them
df.isna().sum()

pclass          0
survived        0
name            0
sex             0
age           263
sibsp           0
parch           0
ticket          0
fare            1
cabin        1014
embarked        2
boat          823
body         1188
home.dest     564
dtype: int64

In [7]:
# Remove incomplete categories for easier processing
df = df.dropna(subset = ['fare', 'embarked'])

In [8]:
# Remove unnecessary categories for easier processing
df = df.drop(['cabin', 'body', 'boat', 'name', 'home.dest'], axis = 1)

In [9]:
# Fill empty spots and the meaning of the categories
df['age'].fillna(value = df['age'].mean(),  inplace = True)

In [10]:
# Supervised clustering to ensure all the data works
df.dtypes

pclass        int64
survived      int64
sex          object
age         float64
sibsp         int64
parch         int64
ticket       object
fare        float64
embarked     object
dtype: object

In [11]:
# Categories for dummy code entered due to not being compatible
df = pd.get_dummies(df, columns = ['sex'])
df = pd.get_dummies(df, columns = ['embarked'])

In [12]:
# Dummy Code
df =df[['survived','pclass','age','sibsp','parch','sex_female','fare','embarked_C','embarked_S']] 

# Seperating Data
X_Vs = df.iloc[:,1:10].values # Independent
Y_V = df.iloc[:,0] # Dependent

In [13]:
df

survived  pclass        age  sibsp  parch  sex_female      fare  \
0            1       1  29.000000      0      0           1  211.3375   
1            1       1   0.916700      1      2           0  151.5500   
2            0       1   2.000000      1      2           1  151.5500   
3            0       1  30.000000      1      2           0  151.5500   
4            0       1  25.000000      1      2           1  151.5500   
...        ...     ...        ...    ...    ...         ...       ...   
1304         0       3  14.500000      1      0           1   14.4542   
1305         0       3  29.813199      1      0           1   14.4542   
1306         0       3  26.500000      0      0           0    7.2250   
1307         0       3  27.000000      0      0           0    7.2250   
1308         0       3  29.000000      0      0           0    7.8750   

      embarked_C  embarked_S  
0              0           1  
1              0           1  
2              0           1  
3              0           1  
4              0           1  
...          ...         ...  
1304           1           0  
1305           1           0  
1306           1           0  
1307           1           0  
1308           0           1  

[1306 rows x 9 columns]

In [14]:
# Split into subsets
from sklearn.model_selection import train_test_split

# Training and Testing
train_X, test_X, train_Y, test_Y = train_test_split(X_Vs, Y_V, test_size = 0.3, random_state = 0)

In [15]:
# Supervised Clustering takes place
def models(train_X, train_Y):
    # Tree Classifier
    from sklearn.tree import DecisionTreeClassifier
    tree = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
    tree.fit(train_X, train_Y)
    
    print('Decision Tree Training Accuracy:', tree.score(train_X, train_Y))
    # Random Forest Classifer
    from sklearn.ensemble import RandomForestClassifier
    rforest = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
    rforest.fit(train_X, train_Y)
    
    print('Random Forest Training Accuracy:', rforest.score(train_X, train_Y))
    return tree, rforest

In [16]:
# Model Training
model = models(train_X, train_Y)

Decision Tree Training Accuracy: 0.9726477024070022
Random Forest Training Accuracy: 0.9584245076586433


In [17]:
from sklearn.metrics import confusion_matrix # Create a confusion matrix
for i in range(len(model)):
    confm = confusion_matrix(test_Y, model[i].predict(test_X))
    
    TN, FP, FN, TP = confusion_matrix(test_Y, model[i].predict(test_X)).ravel()
    print(confm) # Prints Confusion Matrix
    print('Model[{}] Testing Accuracy = "{} !"'.format(i, (TP + TN) / (TP + TN + FN + FP)))
    print() # Adds space between the prints

[[199  42]
 [ 43 108]]
Model[0] Testing Accuracy = "0.7831632653061225 !"

[[211  30]
 [ 44 107]]
Model[1] Testing Accuracy = "0.8112244897959183 !"



In [21]:
#Start of Unsupervised Clustering
from sklearn.cluster import KMeans
y = np.array(df['survived'])
kmean = KMeans(n_clusters = 2)
kmean.fit(X_Vs)

/Users/luthorcorp/anaconda3/lib/python3.11/site-packages/sklearn/cluster/_kmeans.py:1412: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


KMeans(n_clusters=2)

In [22]:
# Accuracy
correct = 0
for i in range(len(X_Vs)):
    predct = np.array(X_Vs[i].astype(float))
    predct = predct.reshape(-1, len(predct))
    predct = kmean.predict(predct)
    if predct[0] == y[i]:
        correct += 1
Accuracy = (correct/len(X_Vs))*100
# Print Accuracy
print('Model Accuracy:', Accuracy)

Model Accuracy: 35.758039816232774


In [23]:
# Unsupervised Predicting
pred = kmean.predict(X_Vs)
# Printing Pred
pred

array([0, 0, 0, ..., 1, 1, 1], dtype=int32)

In [24]:
# Comparing Predicted Values to Actual Values
actuals = df['survived'].value_counts().values
predicted = [len(pred[pred == 0]), len(pred[pred == 1])]
conf_matrix = pd.DataFrame({'0': actuals, '1': predicted}, columns = ['0', '1'])
# Generate Confusion Matrix with Data
conf_matrix

0     1
0  808    71
1  498  1235

In [25]:
# Jupyter Notebook helped alot with the testing and running the code back. 
# I still prefer VS Code for my HTML and CSS functions. 
# But this was easier to use with the Python.
# Jupyter Notebook was difficult in terms of locating the errors within the lines of code.